# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/kobuki_qtestsuite/ui/life_frame.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_life_frame(object):
    def setupUi(self, life_frame):
        life_frame.setObjectName("life_frame")
        life_frame.resize(791, 414)
        life_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        life_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayout_2 = QtWidgets.QGridLayout(life_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.text_browser = QtWidgets.QTextBrowser(life_frame)
        self.text_browser.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.text_browser.setTabChangesFocus(True)
        self.text_browser.setDocumentTitle("")
        self.text_browser.setSource(QtCore.QUrl("qrc:/text/life.html"))
        self.text_browser.setOpenLinks(False)
        self.text_browser.setObjectName("text_browser")
        self.gridLayout_2.addWidget(self.text_browser, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(life_frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 89, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.run_progress = QtWidgets.QProgressBar(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_progress.sizePolicy().hasHeightForWidth())
        self.run_progress.setSizePolicy(sizePolicy)
        self.run_progress.setMaximum(60)
        self.run_progress.setProperty("value", 0)
        self.run_progress.setObjectName("run_progress")
        self.verticalLayout.addWidget(self.run_progress)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.idle_progress = QtWidgets.QProgressBar(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idle_progress.sizePolicy().hasHeightForWidth())
        self.idle_progress.setSizePolicy(sizePolicy)
        self.idle_progress.setMaximum(15)
        self.idle_progress.setProperty("value", 0)
        self.idle_progress.setInvertedAppearance(False)
        self.idle_progress.setObjectName("idle_progress")
        self.verticalLayout.addWidget(self.idle_progress)
        spacerItem1 = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(life_frame)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(96, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.angular_speed_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.angular_speed_spinbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.angular_speed_spinbox.setPrefix("")
        self.angular_speed_spinbox.setMaximum(3.14)
        self.angular_speed_spinbox.setSingleStep(0.1)
        self.angular_speed_spinbox.setProperty("value", 0.8)
        self.angular_speed_spinbox.setObjectName("angular_speed_spinbox")
        self.gridLayout.addWidget(self.angular_speed_spinbox, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(96, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(181, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.start_button = QtWidgets.QPushButton(self.groupBox)
        self.start_button.setObjectName("start_button")
        self.gridLayout.addWidget(self.start_button, 1, 1, 1, 1)
        self.stop_button = QtWidgets.QPushButton(self.groupBox)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout.addWidget(self.stop_button, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(167, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 2)

        self.retranslateUi(life_frame)
        QtCore.QMetaObject.connectSlotsByName(life_frame)

    def retranslateUi(self, life_frame):
        _translate = QtCore.QCoreApplication.translate
        life_frame.setWindowTitle(_translate("life_frame", "Frame"))
        self.groupBox_2.setTitle(_translate("life_frame", "Life Meters"))
        self.label.setText(_translate("life_frame", "Run Status"))
        self.label_4.setText(_translate("life_frame", "Idle Status"))
        self.groupBox.setTitle(_translate("life_frame", "Controls"))
        self.label_3.setText(_translate("life_frame", "Angular Speed"))
        self.angular_speed_spinbox.setSuffix(_translate("life_frame", " rad/s"))
        self.start_button.setText(_translate("life_frame", "Start"))
        self.stop_button.setText(_translate("life_frame", "Stop"))

import common_rc
import text_rc
