# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/kobuki_qtestsuite/ui/wandering_frame.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wandering_frame(object):
    def setupUi(self, wandering_frame):
        wandering_frame.setObjectName("wandering_frame")
        wandering_frame.resize(791, 414)
        wandering_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        wandering_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayout_2 = QtWidgets.QGridLayout(wandering_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.text_browser = QtWidgets.QTextBrowser(wandering_frame)
        self.text_browser.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.text_browser.setTabChangesFocus(True)
        self.text_browser.setDocumentTitle("")
        self.text_browser.setSource(QtCore.QUrl("qrc:/text/wandering.html"))
        self.text_browser.setOpenLinks(False)
        self.text_browser.setObjectName("text_browser")
        self.gridLayout_2.addWidget(self.text_browser, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(wandering_frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 65, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.left_bump_counter_lcd = QtWidgets.QLCDNumber(self.groupBox_2)
        self.left_bump_counter_lcd.setObjectName("left_bump_counter_lcd")
        self.verticalLayout.addWidget(self.left_bump_counter_lcd)
        self.centre_bump_counter_lcd = QtWidgets.QLCDNumber(self.groupBox_2)
        self.centre_bump_counter_lcd.setObjectName("centre_bump_counter_lcd")
        self.verticalLayout.addWidget(self.centre_bump_counter_lcd)
        self.right_bump_counter_lcd = QtWidgets.QLCDNumber(self.groupBox_2)
        self.right_bump_counter_lcd.setObjectName("right_bump_counter_lcd")
        self.verticalLayout.addWidget(self.right_bump_counter_lcd)
        spacerItem1 = QtWidgets.QSpacerItem(20, 119, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(wandering_frame)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(96, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.speed_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.speed_spinbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speed_spinbox.setPrefix("")
        self.speed_spinbox.setMaximum(0.7)
        self.speed_spinbox.setSingleStep(0.1)
        self.speed_spinbox.setProperty("value", 0.3)
        self.speed_spinbox.setObjectName("speed_spinbox")
        self.gridLayout.addWidget(self.speed_spinbox, 0, 2, 1, 1)
        self.angular_speed_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.angular_speed_spinbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.angular_speed_spinbox.setPrefix("")
        self.angular_speed_spinbox.setMaximum(3.14)
        self.angular_speed_spinbox.setSingleStep(0.1)
        self.angular_speed_spinbox.setProperty("value", 0.8)
        self.angular_speed_spinbox.setObjectName("angular_speed_spinbox")
        self.gridLayout.addWidget(self.angular_speed_spinbox, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(96, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(181, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 2)
        self.start_button = QtWidgets.QPushButton(self.groupBox)
        self.start_button.setObjectName("start_button")
        self.gridLayout.addWidget(self.start_button, 1, 2, 1, 1)
        self.stop_button = QtWidgets.QPushButton(self.groupBox)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout.addWidget(self.stop_button, 1, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(167, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 4, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 2)

        self.retranslateUi(wandering_frame)
        QtCore.QMetaObject.connectSlotsByName(wandering_frame)

    def retranslateUi(self, wandering_frame):
        _translate = QtCore.QCoreApplication.translate
        wandering_frame.setWindowTitle(_translate("wandering_frame", "Frame"))
        self.groupBox_2.setTitle(_translate("wandering_frame", "Bump Counter"))
        self.groupBox.setTitle(_translate("wandering_frame", "Controls"))
        self.label_2.setText(_translate("wandering_frame", "Speed"))
        self.speed_spinbox.setSuffix(_translate("wandering_frame", " m/s"))
        self.angular_speed_spinbox.setSuffix(_translate("wandering_frame", " rad/s"))
        self.label_3.setText(_translate("wandering_frame", "Angular Speed"))
        self.start_button.setText(_translate("wandering_frame", "Start"))
        self.stop_button.setText(_translate("wandering_frame", "Stop"))

import common_rc
import text_rc
